### ISSUE TITLE
Trouble downloading dataset from google drive

### ISSUE THREAD

**Issue by rafaelorozco** [lanl/OpenFWI#1]
Hello, 

Thank you for making this cool dataset. I am currently having trouble automatically downloading the dataset from google drive. I cant find a way to download whole folders instead I am being forced to download file by file. Could you tell me how a dataset ie CurveFault_b could be downloaded in one go with a single link?

I think that part of the problem is that the links are not completely public so tools like gdown fail. 

Thank you for your attention

**Comment by Shihang-LANL** [comment]
Hi,
Sorry for the late reply. Currently, we only allow downloads from google drive. You can use "shift" to select multi files and download them all. If you still meet problems, please let me now.
Best regards,
Shihang
