### ISSUE TITLE
Data generation code

### ISSUE THREAD

**Issue by CarlosGDCJ** [lanl/OpenFWI#12]
Is the data generation code available anywhere? I couldn't find it in the repository.

**Comment by Shihang-LANL** [comment]
The data generation code is not released, but you can find a MATLAB version of the forward modeling code at [this link](https://csim.kaust.edu.sa/files/SeismicInversion/Chapter.FD/lab.FD2.8/lab.html). Our code exactly follows this MATLAB code and translates it to Python. The parameters of the MATLAB code should be used.

nz=70; nx=70;
dx=10; nbc=120; nt=1001; dt=0.001;
freq=15; s=ricker(freq,dt); isFS=false;
coord.sx = 1*dx; coord.sz = 1*dx;
coord.gx=(1:nx)*dx; coord.gz=ones(size(coord.gx))*dx;

**Comment by CarlosGDCJ** [comment]
I see, I was actually more interested in the code that creates the velocity models. A shame it wasn't released. But knowing the forward modeling is helpful nonetheless. Thanks for the info.
