### ISSUE TITLE
Set environment for PyTorch - GPU

### ISSUE THREAD

**Issue by Abdelhameed88** [lanl/OpenFWI#2]
Hello all,

Thanks for your effort and publish this great code.

Please, I have an issue on setup the environment to run the code for FlatVel-a. I set up the environment using the following commands:

- conda create --name torch python=3.8
- conda activate torch
- conda install pytorch-gpu torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia

However, I got the following error:

I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.

To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

Please, any advice.

Thanks in advance,
Ahmed

**Comment by Shihang-LANL** [comment]
Hi, Ahmed

The error you're encountering appears to be related to TensorFlow. However, this specific package does not utilize any TensorFlow functions. It's possible that you have TensorFlow installed in your default path, which can cause compatibility issues with PyTorch. To resolve this, I recommend uninstalling TensorFlow before using PyTorch. 
Here are the required packages for this code to work properly, the packages other than these may cause imcompatibility:
    pytorch v1.7.1
    torchvision v0.8.2
    scikit learn
    numpy
    matplotlib (for visualization)

Best regards,
Shihang

**Comment by Abdelhameed88** [comment]
Many thanks Shihang for your suggestions. It works now.

Best regards,
Ahmed
