### ISSUE TITLE
Request for Access to InversionNet3D Code

### ISSUE THREAD

**Issue by Alicia1201** [lanl/OpenFWI#4]
Hello author,  we are currently working on a project related to your research, and we plan to conduct a series of comparative experiments on our own data to further assess the performance of InversionNet3D and other methods in a specific application. We kindly request that you provide access to the code for InversionNet3D, as it would greatly facilitate our in-depth research and experimentation. Thank you for your time and support.

**Comment by hanchenwang** [comment]
Hi Alicia,
We are currently working on releasing the InversionNet3D code. However, it is still under review by the US DOE, and it will take a few months to get the approval. Hopefully, the code will be open-sourced in January 2024. Sorry for the inconvenience.
If anything else we can help, please kindly let us know. 
Best,
-Hanchen Wang

**Comment by Alicia1201** [comment]
Thank you for your response and for providing an update on the status of the InversionNet3D code. I genuinely appreciate the hard work you're putting into making the code open-source. Best regards!
